namespace Jellyfish.Transactions;

/// <summary>
/// WitnessScript just hold bytes array that is going to be pushed into the stack.
/// It does not follow the same semantic as Script.
/// 
/// For P2WSH, the last item in the witness (the "witnessScript") is popped off, hashed with SHA256,
/// compared against the 32-byte-hash in scriptPubKey, and deserialized as a Script.
/// </summary>
public class WitnessScript
{
    /// <summary>
    /// Witness script stored as LITTLE ENDIAN hex string.
    /// It MUST BE STRIPPED of VarUInt{1-9 bytes}, those bytes will be generated by the composer.
    /// </summary>
    public string Hex { get; init; } = string.Empty;
}
